---@meta
---lib/map_data.lua - STATIC Dota map positions (fallback table). Hero-agnostic.
---GENERATED by tools/gen_map_data.lua from a Tinker dump_positions() run; do not hand-edit.
---Tier: 0=small 1=medium 2=large 3=ancient. Coords = centered system. Teams: 2=Radiant 3=Dire.

local MapData = {}

MapData.TIER = { [0]="small", [1]="medium", [2]="large", [3]="ancient" }

MapData.CAMPS = {  -- 28 camp spawners
  { tier=1, center={-1962,-4740,312}, box={-2304,-5088,-1619,-4393} },
  { tier=3, center={4099,63,214}, box={3528,-402,4670,528} },
  { tier=3, center={-4797,-104,292}, box={-5349,-592,-4245,385} },
  { tier=1, center={193,-5154,108}, box={-251,-5532,636,-4776} },
  { tier=2, center={-1512,-3458,-20}, box={-2036,-3881,-988,-3034} },
  { tier=2, center={4751,-3904,56}, box={4379,-4313,5122,-3495} },
  { tier=1, center={-766,4912,86}, box={-1216,4520,-316,5304} },
  { tier=1, center={3392,-1216,300}, box={3008,-1536,3776,-896} },
  { tier=0, center={4045,-5043,94}, box={3647,-5438,4443,-4648} },
  { tier=2, center={7937,-57,204}, box={7617,-409,8257,295} },
  { tier=2, center={-4854,3991,98}, box={-5212,3584,-4496,4398} },
  { tier=1, center={1152,4096,-20}, box={783,3772,1521,4420} },
  { tier=1, center={-4032,895,44}, box={-4368,535,-3696,1255} },
  { tier=1, center={-769,-7685,-32}, box={-1068,-8019,-469,-7350} },
  { tier=1, center={307,7710,236}, box={-40,7358,654,8062} },
  { tier=2, center={1088,2536,-20}, box={637,2142,1539,2931} },
  { tier=0, center={8448,1216,428}, box={8192,896,8704,1536} },
  { tier=2, center={-8261,-431,204}, box={-8645,-815,-7877,-47} },
  { tier=0, center={-2964,7412,127}, box={-3319,7060,-2609,7764} },
  { tier=1, center={-2568,3857,369}, box={-2923,3543,-2213,4171} },
  { tier=0, center={2671,-8370,16}, box={2344,-8714,2999,-8027} },
  { tier=1, center={1832,-4033,158}, box={1458,-4448,2206,-3618} },
  { tier=0, center={-3940,4946,76}, box={-4260,4550,-3620,5341} },
  { tier=0, center={-7982,-1783,212}, box={-8357,-2173,-7608,-1392} },
  { tier=1, center={2080,7896,250}, box={1629,7524,2531,8268} },
  { tier=1, center={-2480,-8400,-32}, box={-2856,-8768,-2104,-8032} },
  { tier=1, center={4399,-8290,16}, box={4072,-8634,4727,-7947} },
  { tier=1, center={-4240,8256,127}, box={-4595,7904,-3885,8608} },
}

MapData.TOWERS = {
  { name="dota_goodguys_tower3_bot", team=2, pos={-3952,-6112,256} },
  { name="dota_goodguys_tower3_mid", team=2, pos={-4640,-4144,256} },
  { name="dota_goodguys_tower3_top", team=2, pos={-6592,-3408,256} },
  { name="dota_goodguys_tower2_bot", team=2, pos={-360,-6256,128} },
  { name="dota_goodguys_tower1_bot", team=2, pos={4860,-6379,128} },
  { name="dota_goodguys_tower2_mid", team=2, pos={-3190,-2926,128} },
  { name="dota_goodguys_tower2_top", team=2, pos={-6501,-872,128} },
  { name="dota_goodguys_tower1_top", team=2, pos={-6336,1856,128} },
  { name="dota_goodguys_tower4_top", team=2, pos={-5712,-4864,256} },
  { name="dota_badguys_fort", team=3, pos={5528,5000,248} },
  { name="dota_goodguys_fort", team=2, pos={-5920,-5352,240} },
  { name="dota_badguys_tower4_top", team=3, pos={4944,4776,256} },
  { name="dota_badguys_tower2_top", team=3, pos={-128,6016,128} },
  { name="dota_badguys_tower1_top", team=3, pos={-5275,6036,128} },
  { name="dota_badguys_tower2_mid", team=3, pos={2496,2112,128} },
  { name="dota_badguys_tower1_mid", team=3, pos={524,652,128} },
  { name="dota_badguys_tower2_bot", team=3, pos={6400,384,128} },
  { name="dota_badguys_tower3_bot", team=3, pos={6336,3032,256} },
  { name="dota_badguys_tower3_top", team=3, pos={3552,5776,256} },
  { name="dota_badguys_tower3_mid", team=3, pos={4272,3759,256} },
  { name="dota_badguys_tower4_bot", team=3, pos={5280,4432,256} },
  { name="dota_goodguys_tower4_bot", team=2, pos={-5392,-5192,256} },
  { name="dota_goodguys_tower1_mid", team=2, pos={-1544,-1408,128} },
  { name="dota_badguys_tower1_bot", team=3, pos={6269,-2240,128} },
}

MapData.OUTPOSTS = {
  { name="npc_dota_watch_tower_bottom", team=2, pos={-4096,-448,256} },
  { name="npc_dota_watch_tower_top", team=3, pos={3392,-448,256} },
}

MapData.FOUNTAINS = {
  { name="ent_dota_fountain_bad", team=3, pos={7408,6848,377} },
  { name="ent_dota_fountain_good", team=2, pos={-7456,-6938,393} },
}

-- Side-lane creep SPAWNS (in-client captured, v0.1.113-116 wave-mirror instrumentation; hand-added,
-- not from gen_map_data). Mid spawns were not reliably captured (bot-contaminated sample) - the mid
-- lane path ends at the T3s, which is equivalent for arc-length mirroring. Piece 1.5.
MapData.SPAWNS = {
  { team=2, lane="top", pos={-6608,-4064,256} },
  { team=2, lane="bot", pos={-3600,-6152,256} },
  { team=3, lane="top", pos={3173,5761,256} },
  { team=3, lane="bot", pos={6272,3648,256} },
}

return MapData
